# Generated by Django 4.0.6 on 2022-08-10 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynfilters', '0005_alter_dynamicfilterexpr_is_global'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dynamicfilterexpr',
            name='is_global',
            field=models.BooleanField(db_index=True, default=False, help_text='Make filter accessible to all.', verbose_name='Global?'),
        ),
    ]
